# -*- coding: utf-8 -*-
"""clarify1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zDQO2K_N_YsAjENxv3jvjJ6bYSZQacaM
"""

print("Olá São Paulo")
print('Enzo "Super" Rocha')

"""Trabalhando com tipificação e variáveis."""

nome = "Enzo" #string
sobrenome = "Rocha"
idade = 20 #interger
altura = 1.77 #float
bermuda = False #boolean

print (nome + " " + sobrenome + " tem " + str(idade) + " anos")
print(idade + 2)
texto_varias_linhas = '''
operadores
soma +
subtração -
divisão /
multiplicação
'''
print(texto_varias_linhas)

"""Detalhando strings e usando formato"""

nomeCompleto = "Enzo Python Rocha"
inicio = 4
fim = inicio + 6
print(nomeCompleto[inicio:fim])

nome = input("Qual seu nome")
sobrenome = input("Qual seu sobrenome")
print("Seu nome completo é: " + nome + "" + sobrenome)

primeiroNumero = input("Qual o numero:")
segundoNumero = input("Qual segundo numero:")
print(int(primeiroNumero) + int(segundoNumero))

"""Projeto Calculadora"""

valor01= int(input("Escolha seu primeiro valor"))
escolhas = '''
[1] - Soma
[2] - Subtração
[3] - Divisão
[4] - Multiplicação
[5] - Potencia
[0] - Sair
'''
print(escolhas)
operador = input("Selecione sua opção")
while operador == "0":
  print("Obrigado por usar a calculadora")
  break

valor02 = input("Escolha seu segundo valor")

valor01 = int(valor01)
valor02 = int(valor02)
if operador == "1" :
  resultado = valor01 + valor02
  print("Resultado é: " + str(resultado))

if operador == "2" :
    resultado = valor01 - valor02
    print("Resultado é: " + str(resultado))

if operador == "3" :
  resultado = valor01 / valor02
  print("Resultado é: " + str(resultado))

if operador == "4" : 
  resultado = valor01 * valor02
  print("Resultado é: " + str(resultado))

if operador == "5" :
  resultado = valor01 ** valor02
  print("Resultado é: " + str(resultado))

salario = float(input("Digite o valor do seu salario para o imposto de renda"))
base = salario
imposto = 0
if base > 3000:
  imposto = imposto + ((base - 3000) * 0.35 )
if base > 1000:
  imposto = imposto +((base-1000)* 0.20)
print("salario: R$%6.2f imposto a pagar: R$%6.2f" % (salario,imposto))

from inspect import signature
from IPython.core import interactiveshell
from random import randint

print('#### Iniciando Jogo ####')

random = randint(0,100)

chute = 0
chances = 10
while chute != random:
  chute = input("Chute um numero aleatorio entre 0 e 100: ")
  if chute.isnumeric():
    chute = int(chute)
    chances = chances - 1
    if chute == random:
      print('')
      print('Parabens, voce venceu! O numero era {} e voce ainda tinha {} chances'.format (random,chances))
      print('')
      break
    else:
      print('')
      if chute > random:
        print('Voce errou! O numero era menor!')
        print('Voce ainda tem {} chances'.format(chances))

      if chute < random:
        print('Voce errou! O numero era maior!')
        print('Voce ainda tem {} chances'.format(chances))
        print('')
      if chances == 0:
        print('')
        print('Suas chances acabaram, voce perdeu')
        print('')
        break
print('#### Fim de Jogo ####')

def borajogar(nominho , resp):
    print("vamos brincar!!", nominho, "voce disse que" , resp) 

def semgraca(nomao , resp):
    print("entao tchau seu chato....", nomao, "voce", resp, "sabe brincar")

nome = input('quem ta ai')
resposta = input('voce quer jogar>')

if resposta == "sim":
  borajogar(nome, resposta)

if resposta == "nao":
  semgraca(nome, resposta)
  nome = ""